Bump version of survey-react-ui
I experienced a bug whereby upgrading survey-creator-react through yarn made everything break with an error `TypeError: this.item.getActionBarItemActiveCss is not a function`.

After some digging it appears the `getActionBarItemActiveCss` was added to `Action` in version `1.9.7` (link)[https://github.com/surveyjs/survey-library/commit/0630d2a6bffe7278ed20dc31e5612314d5d79bf0]

So this needs to be the minimum version depended upon.